/**
 * @inbox/contracts — shared types, Zod schemas, and enums for the Inbox messaging system.
 *
 * This package is the single source of truth for JSON contract shapes
 * between the bash CLI, BFF server, and React UI.
 */

// Enums (runtime constants + types)
export {
  AddressKind,
  ChangeKind,
  Classification,
  DeliveryEventType,
  EffectiveRole,
  EngagementState,
  ErrorCode,
  ExitCode,
  PrivateRecipientRole,
  RecipientRole,
  RefKind,
  SourceKind,
  Urgency,
  ViewKind,
  VisibilityState,
  errorToExit,
} from "./enums.js";

// Zod schemas (runtime validators)
export {
  // Primitives
  addressStr,
  conversationId,
  deliveryId,
  feedbackId,
  messageId,
  prefixedId,
  timestampMs,
  // Enum schemas
  addressKindSchema,
  effectiveRoleSchema,
  engagementStateSchema,
  errorCodeSchema,
  recipientRoleSchema,
  refKindSchema,
  urgencySchema,
  viewKindSchema,
  visibilityStateSchema,
  // Shared fragments
  addressSummarySchema,
  deliveryStateSchema,
  referenceSchema,
  resolutionSummarySchema,
  sentStateSchema,
  threadReferenceSchema,
  // Error envelopes
  comingSoonErrorSchema,
  errorDetailSchema,
  errorEnvelopeSchema,
  // Command responses
  directoryListResponseSchema,
  directoryMembersResponseSchema,
  directoryShowResponseSchema,
  giveFeedbackResponseSchema,
  listItemSchema,
  listResponseSchema,
  messageContentSchema,
  mutationResponseSchema,
  readResponseSchema,
  replyResponseSchema,
  sendResponseSchema,
  sentListItemSchema,
  sentListResponseSchema,
  sentMutationResponseSchema,
  sentReadResponseSchema,
  threadItemSchema,
  threadResponseSchema,
  whoamiResponseSchema,
  // Experiments
  experimentStatusSchema,
  experimentVariantSchema,
  experimentSchema,
  experimentListResponseSchema,
  // Feedback board
  feedbackSentimentSchema,
  feedbackEntrySchema,
  feedbackBoardResponseSchema,
  // Delivery events (inspector)
  deliveryEventTypeSchema,
  deliveryEventSchema,
  deliveryEventListResponseSchema,
  // Analytics (workflow dashboard)
  analyticsTimeWindowSchema,
  analyticsTopEntrySchema,
  analyticsOverviewResponseSchema,
  analyticsOverviewQuerySchema,
  // BFF request / query schemas (OpenAPI track)
  recipientInputSchema,
  sendRequestSchema,
  replyRequestSchema,
  inboxQuerySchema,
  inboxReadQuerySchema,
  sentQuerySchema,
  threadQuerySchema,
  directoryQuerySchema,
  eventsQuerySchema,
  errorResponseSchema,
} from "./schemas.js";

// TypeScript types (zero-cost, type-only)
export type {
  AddressSummary,
  CliResponse,
  ComingSoonError,
  DeliveryEvent,
  DeliveryEventKind,
  DeliveryEventListResponse,
  DeliveryState,
  DirectoryListResponse,
  DirectoryMembersResponse,
  DirectoryShowResponse,
  ErrorDetail,
  ErrorEnvelope,
  Experiment,
  ExperimentListResponse,
  ExperimentStatus,
  ExperimentVariant,
  FeedbackBoardResponse,
  FeedbackEntry,
  FeedbackSentiment,
  GiveFeedbackResponse,
  ListItem,
  ListResponse,
  MessageContent,
  MutationResponse,
  ReadResponse,
  Reference,
  ReplyResponse,
  ThreadReference,
  ResolutionSummary,
  SendResponse,
  SentListItem,
  SentListResponse,
  SentMutationResponse,
  SentReadResponse,
  SentState,
  SuccessResponse,
  ThreadItem,
  ThreadResponse,
  WhoamiResponse,
  // Analytics types (workflow dashboard)
  AnalyticsTimeWindow,
  AnalyticsTopEntry,
  AnalyticsOverviewResponse,
  AnalyticsOverviewQuery,
  // BFF request / query types
  SendRequest,
  ReplyRequest,
  InboxListQuery,
  InboxReadQuery,
  SentListQuery,
  ThreadQuery,
  DirectoryListQuery,
  EventsQuery,
  ErrorResponse,
} from "./types.js";
